networks:
  deploy-dev:
    driver: bridge
services:
  identity:
    container_name: gateway-service
    image: gateway-service
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 5050
    ports:
      - "5050:5050"
    networks:
      - deploy-dev
